FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
env_variables:
  BOT_TOKEN: "7691575845:AAGqhk8hljWq53SrHKDQRO09PEjyGt5DSCk" 